#默认使用配置
spring:
  port: 9090
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: cn.yyff.tax.cxf.bean
  mapperLocations: classpath:mapping/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/depot?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver